version: '3.8'
services:
  app:
    container_name: nextjs-prod
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    
    env_file:
      - .env.local
      - .env
  
  caddy:
    image: caddy:latest
    restart: unless-stopped
    user: root
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./caddy_config/Caddyfile:/etc/caddy/Caddyfile
    
    environment:
      - CADDY_DOMAIN={CADDY_DOMAIN}

    env_file:
      - .env.local

networks:
  default:
    name: caddy_net