name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
        CADDY_DOMAIN: ${{ secrets.CADDY_DOMAIN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        docker compose -f docker-compose.prod.yml down
        docker compose -f docker-compose.prod.yml build
        docker compose -f docker-compose.prod.yml up -d
